### PR TITLE
Require newlines inbetween import groups

### PR DESCRIPTION
**Pull request by giodamelio**
First off I wanted to say thanks for making this config. We agree on almost everything style wise, which I have not found in any other config preset. I am not sure what your process is for adding new rules, so I figured I would just send a pull.

It is just one simple change, but I have always liked keeping my [import types separate](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#newlines-between-ignorealwaysnever).

Also, I wasn't sure what the scope in the commit message should be, I can change it if need be.

### CODE REVIEW

**Comment by giodamelio** [comment]
Oops, forgot to run the tests. I love how your linter lints itself. :smile: I will push a fix.

**Comment by scottnonnenberg** [comment]
Hey there! Glad you're finding this project useful! :0)

I just tested it on my current `import`-using project, and I didn't like that it wanted me to get rid of the line breaks for this code:

```
import stats from 'simple-statistics';

import forEach from 'lodash/forEach';
import map from 'lodash/map';

import flow from 'lodash/fp/flow';
import sortBy from 'lodash/fp/sortBy';
import groupBy from 'lodash/fp/groupBy';
import transform from 'lodash/fp/transform';
```

Yes, I understand that they're all the 'node modules' category, but they are organized conceptually! If the rule allowed me to put a newline wherever I wanted, but would force me to separate the various categories of imports, I'd be okay with it. :0(

**Comment by giodamelio** [comment]
Hmm, that does seem nicer. It looks like the `import/order` does not allow configuring of newlines inside import groups.

> If set to always, at least one new line between each group will be enforced, and new lines inside a group will be forbidden.

I just made an issue at benmosher/eslint-plugin-import#627, hopefully I will be ok'd to contribute a new setting to eslint-plugin-import that will take care of this.

**Comment by scottnonnenberg** [comment]
Great to see the progress on https://github.com/benmosher/eslint-plugin-import/issues/627 - I'm excited. :0)

**Comment by giodamelio** [comment]
Hopefully I can get it accepted soon.

**Comment by giodamelio** [comment]
Closing this because I accidentally created it from my forks master branch which is making it difficult to make other pull requests. I will make another pull when benmosher/eslint-plugin-import#628 lands.

**Comment by scottnonnenberg** [comment]
Sounds good.

**Pull request closed without merging**
