### PR TITLE
Replace deprecated ghooks with husky

### PR DESCRIPTION
**Pull request by giodamelio**
When I was working on #4 I noticed that [`ghooks`](https://github.com/gtramontina/ghooks) has been deprecated in favor of [`husky`](https://github.com/typicode/husky). So I threw together a quick pull to migrate to it. It's pretty straightforward except you have to delete all your git hooks(`rm .git/hooks/*`) before you install husky to allow it to make it's own.

### CODE REVIEW

**Comment by scottnonnenberg** [comment]
I hadn't heard about that - thanks for the heads-up and change! One request - can you change the version from `^0.12.0` to just plain `0.12.0`?

**Comment by giodamelio** [comment]
Done

**Comment by giodamelio** [comment]
Done for real this time. Gotta remember those `git add`'s...

**Comment by scottnonnenberg** [comment]
Thanks. Got this working only after [updating `standard-version`](https://github.com/scottnonnenberg/eslint-config-thehelp/commit/9c7e03ad059146326295338e1780892f5835cda1), which was [blowing up on npm's meta-output on stderr](https://github.com/conventional-changelog/standard-version/pull/110).

**Pull request merged**
